version: "3.9"

services: 
  api:
    image: flobbe9/word_light_frontend
    container_name: word_light_frontend
    ports:
      - ${PORT}:${PORT}
    environment:
      # replace prod ip for local testing
    - API_HOST=localhost