version: "3.9"

services: 
  frontend:
    image: flobbe9/vorspiel_frontend
    container_name: vorspiel_frontend
    ports:
      - 3000:3000

  db:
    image: mysql
    container_name: vorspiel_db
    ports:
        - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: vorspiel

  # mailserver:
  #     image: maildev/maildev
  #     container_name: vorspiel_mail_server_test
  #     ports:
  #         - 1080:1080
  #         - 1025:1025

  backend:
    depends_on: 
      - db
      # - mailserver
    build: .
    image: flobbe9/vorspiel_backend
    container_name: vorspiel_backend
    ports:
        - 4001:4001
