version: "3.9"

# inside dev or stage branch
services: 
  api:
    build:  
      context: .
      args:
        - PORT=${PORT}
    container_name: word_light_frontend-single
    ports:
      - ${PORT}:${PORT}