name: word-light_frontend main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - run: npm ci
      
      - run: npm run build
        env: 
          CI: ""

  push_to_DockerHub:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/word_light_frontend:latest
          build-args: |
            SSL_PASSWORD=${{ secrets.SSL_PASSWORD }}
            SSL_CRT_FILE=word_light.crt.pem
            SSL_KEY_FILE=word_light.key.pem
            SSL_KEYSTORE_FILE=word_light.p12

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: push_to_DockerHub

    # TODO: is data deleted when updating db image?
    steps:
      - name: install sshpass
        run: apt-get install sshpass
      - name: establish ssh tunnel
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USER_NAME }}@word-light.de
      - name: pull new images
        run: docker-compose pull
      - name: remove containers with dangling images
        run: docker rm $(docker container ls --all --filter=ancestor=$(docker images -f "dangling=true" -q) --format "{{.ID}}") --force
      - name: remove danling imges
        run: docker image rm $(docker images -f "dangling=true" -q)
      - name: start new docker images
        run: docker-compose up