name: word-light_frontend stage

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches: 
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - run: npm ci
      
      - run: npm run build
        env: 
          CI: ""